/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddPlaceRouteImport } from './routes/add-place'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as PlacePlaceIdRouteImport } from './routes/place.$placeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaceRoute = AddPlaceRouteImport.update({
  id: '/add-place',
  path: '/add-place',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-place': typeof AddPlaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-place': typeof AddPlaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-place': typeof AddPlaceRoute
  '/discoveries': typeof DiscoveriesRoute
  '/explore': typeof ExploreRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/stories': typeof StoriesRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-place'
    | '/discoveries'
    | '/explore'
    | '/map'
    | '/profile'
    | '/stories'
    | '/place/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-place'
    | '/discoveries'
    | '/explore'
    | '/map'
    | '/profile'
    | '/stories'
    | '/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-place'
    | '/discoveries'
    | '/explore'
    | '/map'
    | '/profile'
    | '/stories'
    | '/place/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPlaceRoute: typeof AddPlaceRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  ExploreRoute: typeof ExploreRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  StoriesRoute: typeof StoriesRoute
  PlacePlaceIdRoute: typeof PlacePlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-place': {
      id: '/add-place'
      path: '/add-place'
      fullPath: '/add-place'
      preLoaderRoute: typeof AddPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPlaceRoute: AddPlaceRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  ExploreRoute: ExploreRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  StoriesRoute: StoriesRoute,
  PlacePlaceIdRoute: PlacePlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
