"""Kenzory development seed content.

Realistic Egyptian heritage examples used to populate a fresh development
database via the `flask seed` command. This content is strictly separated
from application logic: pages always read from the database.
"""

CATEGORIES = [
    "Historical Sites",
    "Hidden Gems",
    "Architecture",
    "Traditional Crafts",
    "Food & Culture",
    "Stories & Legends",
    "Religious Heritage",
    "Natural Heritage",
]

CATEGORY_META = {
    "Historical Sites": {"tone": "cat-historical", "icon": "landmark"},
    "Hidden Gems": {"tone": "cat-hidden", "icon": "compass"},
    "Architecture": {"tone": "cat-architecture", "icon": "map-pin"},
    "Traditional Crafts": {"tone": "cat-crafts", "icon": "sparkles"},
    "Food & Culture": {"tone": "cat-food", "icon": "heart-handshake"},
    "Stories & Legends": {"tone": "cat-stories", "icon": "book-open"},
    "Religious Heritage": {"tone": "cat-religious", "icon": "church"},
    "Natural Heritage": {"tone": "cat-natural", "icon": "mountain"},
}

GOVERNORATES = [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El-Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Minufiya",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
]

PERIODS = [
    "Prehistoric",
    "Ancient Egyptian",
    "Pharaonic",
    "Greco-Roman",
    "Coptic",
    "Early Islamic",
    "Mamluk",
    "Ottoman",
    "Modern",
    "Contemporary",
]

CONTRIBUTORS = {
    "mahmoud": {
        "name": "Mahmoud Nasser",
        "initials": "MN",
        "level": "Heritage Guide",
    },
    "dina": {"name": "Dina El-Sayed", "initials": "DE", "level": "Contributor"},
    "omar": {"name": "Omar Fathy", "initials": "OF", "level": "Contributor"},
    "laila": {"name": "Laila Hassan", "initials": "LH", "level": "Photographer"},
    "karim": {"name": "Karim Aziz", "initials": "KA", "level": "Contributor"},
    "hana": {"name": "Hana Youssef", "initials": "HY", "level": "Contributor"},
    "mariam": {"name": "Mariam Adel", "initials": "MA", "level": "Contributor"},
    "youssef": {"name": "Youssef Tarek", "initials": "YT", "level": "Photographer"},
    "norhan": {"name": "Norhan Ali", "initials": "NA", "level": "Contributor"},
    "khalid": {"name": "Khalid Mansour", "initials": "KM", "level": "Contributor"},
    "sara": {"name": "Sara Ibrahim", "initials": "SI", "level": "Contributor"},
    "mostafa": {"name": "Mostafa Gamal", "initials": "MG", "level": "Contributor"},
}

# ---------------------------------------------------------------------------
# Places
# ---------------------------------------------------------------------------

PLACES = [
    {
        "id": "deir-al-qusayr",
        "name": "Deir Al-Qusayr — The Last Desert Monastery",
        "category": "Religious Heritage",
        "governorate": "Minya",
        "region": "Northern Upper Egypt",
        "period": "Coptic",
        "approxDate": "12th century CE",
        "city": "Maghagha",
        "lat": 28.5721,
        "lng": 30.6862,
        "image": "place-coptic",
        "gallery": ["place-coptic", "beni-hasan", "place-temple"],
        "summary": "A 12th-century desert monastery built around the cave where a bishop's body, laid under a simple arch, never decayed.",
        "description": "Tucked between the desert escarpment and the Nile, Deir Al-Qusayr is a rare fully surviving medieval Coptic monastery: mud-brick domes, a painted wooden ceiling, and a doorway carved with the last iconographic programs of the region. Inside the main church a stone arch still shelters the glass-and-wood reliquary of Bishop Sarapamon, who according to local accounts was found incorrupt after two centuries in the desert heat.",
        "keyFacts": [
            "One of the oldest fully-surviving medieval monasteries in Egypt",
            "Reliquary of Bishop Sarapamon inside the main church",
            "Original painted wood and mud-brick construction",
            "Combines basilica plan with a tower to the north",
            "Recently restored with UNESCO support",
        ],
        "timeline": [
            "c. 4th–6th c. — monastic settlement established in the bay",
            "12th c. — present-day churches and tower built",
            "1850s — a famous earthquake cracks the main church",
            "1900s — Sarapamon's relics relocated to a glass reliquary",
            "2015 — full restoration begins",
        ],
        "architecture": [
            "Mud-brick shell with domes and a heavy tower",
            "Basilica plan divided into five bays",
            "Painted wooden ceiling over the nave",
            "Carved iconostasis and sanctuary screens",
        ],
        "stories": [
            "A Copt once hid in the monastery's tower while soldiers searched below — the ladder was pulled up, and the footsteps passed without entering.",
            "Visitors who stay past sunset report the desert wind sounding like a choir in the empty nave.",
        ],
        "sources": ["Supreme Council of Antiquities", "IOCS restoration archive", "Visitor field notes"],
        "contributor": "mahmoud",
        "addedAgo": "2 weeks ago",
        "saves": 432,
        "photos": 14,
        "rating": 4.9,
        "ratingCount": 61,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 3.5,
    },
    {
        "id": "mosque-al-hamawi",
        "name": "The 'Hidden' Mosque of Al-Hamawi",
        "category": "Religious Heritage",
        "governorate": "Alexandria",
        "region": "Lower Egypt",
        "period": "Ottoman",
        "approxDate": "16th century CE",
        "city": "Alexandria",
        "lat": 31.1923,
        "lng": 29.9016,
        "image": "place-mosque",
        "gallery": ["place-mosque", "sultan-hassan", "place-coptic"],
        "summary": "An Ottoman neighbourhood mosque with an ochre dome, hidden in a bend of a pedestrian lane in old Alexandria.",
        "description": "A small 16th-century mosque with an ochre-painted dome, tucked at the end of a narrow lane where the street bends. Its mihrab still carries an elegant Kufic inscription, and the minaret, half-hidden behind the rooftops, is only visible from the corniche. The dome's coat of ochre paint, rare in Alexandria, is what gives the neighbourhood its affectionate nickname.",
        "keyFacts": [
            "Ottoman-era neighbourhood mosque, 16th century",
            "Rare ochre-painted dome in Alexandria",
            "Original Kufic mihrab inscription",
            "Minaret visible only from the corniche",
            "Sits in a bend of a pedestrian lane",
        ],
        "timeline": [
            "16th c. — built as a neighbourhood mosque",
            "19th c. — dome repainted in ochre",
            "1970s — listed as a heritage building",
            "2019 — restoration of the minaret",
        ],
        "architecture": [
            "Single-domed prayer hall",
            "Ochre-painted dome and slender minaret",
            "Ottoman-style mihrab with Kufic band",
        ],
        "stories": [
            "Locals say the dome was painted ochre to be visible from the sea to sailors who used it as a marker.",
            "The minaret is nicknamed 'the half-hidden one' — it cannot be seen from any street until you are almost at the door.",
        ],
        "sources": ["Alexandria Heritage Trails", "Local neighbourhood archive"],
        "contributor": "omar",
        "addedAgo": "3 weeks ago",
        "saves": 289,
        "photos": 9,
        "rating": 4.7,
        "ratingCount": 38,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 45,
        "distanceKm": 1.2,
    },
    {
        "id": "nubian-village",
        "name": "The Living Nubian Village",
        "category": "Traditional Crafts",
        "governorate": "Aswan",
        "region": "Southern Upper Egypt",
        "period": "Contemporary",
        "approxDate": "Lived tradition",
        "city": "Aswan",
        "lat": 24.1197,
        "lng": 32.9003,
        "image": "place-nubian",
        "gallery": ["place-nubian", "place-palace", "fishawy"],
        "summary": "A village where hand-painted house fronts, colourful baskets and the Nubian language itself are the heritage — a living record of a community that rebuilt after displacement.",
        "description": "West Bank villages like Gharb Aswan carry a living Nubian heritage of painted house fronts, woven palm baskets, and the songs of the Nubian language spoken across generations. After the 1960s displacement, families rebuilt entire villages as deliberate acts of memory — the colours and patterns on the walls are both decoration and document.",
        "keyFacts": [
            "Living Nubian community and language",
            "Hand-painted house fronts throughout the village",
            "Palm-leaf basket weaving tradition",
            "Rebuilt after the 1960s resettlement",
            "Small community museum of Nubian objects",
        ],
        "timeline": [
            "1900s — traditional villages along the river",
            "1960s — displacement during dam construction",
            "1970s–80s — villages rebuilt on the West Bank",
            "Today — museum, workshops, and guesthouses",
        ],
        "architecture": [
            "Painted facades with symbolic motifs",
            "Courtyard houses with palm roofs",
            "Community-built guesthouses",
        ],
        "stories": [
            "When the new village was built, each family first painted the door of their old home's colours — a map of a village that no longer exists.",
        ],
        "sources": ["Village elders' oral history", "Aswan Governorate records"],
        "contributor": "dina",
        "addedAgo": "5 days ago",
        "saves": 511,
        "photos": 21,
        "rating": 4.8,
        "ratingCount": 77,
        "verified": True,
        "featured": True,
        "popular": True,
        "visitMinutes": 120,
        "distanceKm": 4.0,
    },
    {
        "id": "satis-palace",
        "name": "The Abandoned Palace of Satis",
        "category": "Architecture",
        "governorate": "Kafr El-Sheikh",
        "region": "Nile Delta",
        "period": "Modern",
        "approxDate": "1930s CE",
        "city": "Desouk",
        "lat": 31.1220,
        "lng": 30.6477,
        "image": "place-palace",
        "gallery": ["place-palace", "place-railway", "place-temple"],
        "summary": "A once-glorious palace of a Delta cotton baron, now a structure of arches and light in the middle of the city.",
        "description": "An abandoned palace of a cotton baron, built in the 1930s by a French-trained architect. The famous central hall of arches made entirely of lattice and fenestration is a study in light. The palace has been empty since the 1970s; debates about its restoration continue, and it remains one of the Delta's most beautiful ruins.",
        "keyFacts": [
            "Built 1930s by a cotton baron",
            "Famous 'hall of arches' of lattice and fenestration",
            "Empty since the 1970s",
            "Architect trained in Paris",
            "Subject of ongoing restoration debates",
        ],
        "timeline": [
            "1930s — construction and gilded era",
            "1970s — abandonment begins",
            "2000s — listed as heritage",
            "Today — restoration debated",
        ],
        "architecture": [
            "Hall of arches in lattice and glass",
            "Neo-classical facades with Egyptian details",
            "Grand central staircase in stone",
        ],
        "stories": [
            "Locals say the baron planned a mirrored hall so his wife could see every corner of the garden — she never lived to see it finished.",
        ],
        "sources": ["Kafr El-Sheikh municipality records", "Architectural heritage survey"],
        "contributor": "omar",
        "addedAgo": "1 month ago",
        "saves": 378,
        "photos": 16,
        "rating": 4.6,
        "ratingCount": 44,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 60,
        "distanceKm": 2.1,
    },
    {
        "id": "station-deir-sharaf",
        "name": "The Abandoned Station of Deir Sharaf",
        "category": "Architecture",
        "governorate": "Minufiya",
        "region": "Nile Delta",
        "period": "Modern",
        "approxDate": "1890s CE",
        "city": "Deir Sharaf",
        "lat": 30.5071,
        "lng": 31.0041,
        "image": "place-railway",
        "gallery": ["place-railway", "fort-julien", "place-palace"],
        "summary": "A Victorian railway station from the 1890s, with arched doorways and a wooden ticket booth — a preserved slice of Egypt's early railway age.",
        "description": "A Victorian railway station on the line that once connected Tanta to Mit Ghamr, with arched doorways and a wooden ticket booth frozen in time. Its quiet platforms still see local trains pass without stopping. Part of a proposed heritage railway loop, the station stands as a preserved slice of Egypt's early railway age.",
        "keyFacts": [
            "Built in the 1890s Victorian style",
            "Original wooden ticket booth intact",
            "Arched brick doorways",
            "Served the Tanta–Mit Ghamr line",
            "Part of a proposed heritage railway loop",
        ],
        "timeline": [
            "1890s — opened with the delta line",
            "1930s — busiest era, daily express",
            "1980s — passenger service ends",
            "Today — candidate for heritage restoration",
        ],
        "architecture": [
            "Victorian brick station with arched doorways",
            "Wooden ticket booth and original benches",
            "Covered platform with cast-iron columns",
        ],
        "stories": [
            "A retired stationmaster still visits; he keeps the platform clock set to the last departure.",
        ],
        "sources": ["Egyptian Railway Museum archive", "Local rail enthusiast records"],
        "contributor": "karim",
        "addedAgo": "3 weeks ago",
        "saves": 251,
        "photos": 11,
        "rating": 4.5,
        "ratingCount": 29,
        "verified": True,
        "featured": False,
        "popular": False,
        "visitMinutes": 45,
        "distanceKm": 0.8,
    },
    {
        "id": "temple-of-nefertari",
        "name": "The Temple of Nefertari",
        "category": "Historical Sites",
        "governorate": "Aswan",
        "region": "Southern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1265 BCE",
        "city": "Abu Simbel",
        "lat": 22.3373,
        "lng": 31.6256,
        "image": "place-temple",
        "gallery": ["place-temple", "place-nubian", "hibis-temple"],
        "summary": "The smaller of the two Abu Simbel temples, dedicated to Queen Nefertari and the goddess Hathor, with two statues of the queen standing beside her king.",
        "description": "The smaller temple of Abu Simbel, dedicated to Queen Nefertari and Hathor. Its facade pairs four seated statues of Ramesses with two of the queen — at full royal scale, a rare honour. Inside, columns crowned with Hathor heads lead to a sanctuary carved with the queen and the goddess. The temple was relocated piece by piece during the 1960s salvage campaign.",
        "keyFacts": [
            "Dedicated to Queen Nefertari and Hathor",
            "Queen carved at royal scale on the facade",
            "Hathor-headed columns inside",
            "Relocated during the 1960s UNESCO campaign",
            "Southernmost temple of its kind",
        ],
        "timeline": [
            "c. 1265 BCE — carved under Ramesses II",
            "1964–68 — cut and relocated 65m higher",
            "1979 — inscribed as a UNESCO site",
            "Today — open with scheduled visits",
        ],
        "architecture": [
            "Rock-cut facade with six statues",
            "Hathor-crowned columns",
            "Deep sanctuary carved from living rock",
        ],
        "stories": [
            "Workers on the 1960s relocation counted every block twice; the temple was rebuilt from 1,200 numbered pieces.",
        ],
        "sources": ["UNESCO World Heritage records", "Abu Simbel salvage campaign"],
        "contributor": "youssef",
        "addedAgo": "6 days ago",
        "saves": 689,
        "photos": 33,
        "rating": 4.9,
        "ratingCount": 120,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 120,
        "distanceKm": 4.5,
    },
    {
        "id": "beni-hasan",
        "name": "The Rock-Cut Tombs of Beni Hasan",
        "category": "Historical Sites",
        "governorate": "Minya",
        "region": "Northern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 2000 BCE",
        "city": "Minya",
        "lat": 27.9333,
        "lng": 30.8833,
        "image": "beni-hasan",
        "gallery": ["beni-hasan", "speos-artemidos", "place-temple"],
        "summary": "Speckled cliffs above the Nile shelter the painted tombs of Middle Kingdom nomarchs, including Egypt's earliest known wrestling scenes.",
        "description": "The Middle Kingdom rock-cut tombs of Beni Hasan hold some of Egypt's most famous non-royal wall paintings: hunting in the desert, acrobats, and the oldest known wrestling scenes anywhere. The cliff front is so smooth and regular that it reads from the valley as a sheet of pale stone. Among the owners was Khety, a provincial ruler whose tomb doorway is celebrated for its columns.",
        "keyFacts": [
            "Middle Kingdom provincial tombs (c. 2000 BCE)",
            "Earliest known wrestling scenes",
            "Hunting and acrobat paintings",
            "Inscribed doorway of Khety",
            "On the west bank across from Minya",
        ],
        "timeline": [
            "c. 2000 BCE — carved for nomarch families",
            "1830s — first European surveys",
            "1900s — conservation campaigns",
            "Today — scheduled visits by boat",
        ],
        "architecture": [
            "Columned rock-cut porticos",
            "Twelve-columned halls",
            "Deep burial shafts",
        ],
        "stories": [
            "In one tomb, a painter sketched two wrestlers mid-throw; scholars still debate whether the match ends in a pin or a draw.",
        ],
        "sources": ["Newberry's excavation reports", "Minya Governorate heritage office"],
        "contributor": "dina",
        "addedAgo": "2 weeks ago",
        "saves": 344,
        "photos": 17,
        "rating": 4.8,
        "ratingCount": 52,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 5.0,
    },
    {
        "id": "speos-artemidos",
        "name": "Speos Artemidos — The Cave of Artemis",
        "category": "Hidden Gems",
        "governorate": "Minya",
        "region": "Northern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1450 BCE",
        "city": "Beni Hasan",
        "lat": 27.9333,
        "lng": 30.8633,
        "image": "speos-artemidos",
        "gallery": ["speos-artemidos", "beni-hasan", "place-temple"],
        "summary": "A small rock-cut temple to the lioness goddess Pakhet, crowned with a Hatshepsut inscription celebrating her campaigns in Nubia.",
        "description": "A small rock-cut temple dedicated to Pakhet, the lioness goddess of the eastern desert, with an entrance resembling a giant mouth. A Hatshepsut inscription on the lintel recounts her Nubian campaigns, while inside the sanctuary still bears traces of paint. It was described by English travellers who misread Pakhet as 'Artemis' — hence Speos Artemidos.",
        "keyFacts": [
            "Rock-cut temple to the lioness goddess Pakhet",
            "Hatshepsut inscription on the facade",
            "Entrance shaped like a great mouth",
            "Traces of original paint survive",
            "Named by travellers who misread Pakhet as Artemis",
        ],
        "timeline": [
            "c. 1450 BCE — founded under Hatshepsut",
            "Later extended under Alexander's reign",
            "19th c. — described by European travellers",
            "Today — open site, rarely crowded",
        ],
        "architecture": [
            "Facade carved like a giant mouth",
            "Pillared hall and two sanctuaries",
            "Hatshepsut inscription band",
        ],
        "stories": [
            "Travellers in the 1800s who could not name the lioness goddess simply wrote 'Artemis' on their maps — the name stuck.",
        ],
        "sources": ["Epigraphic survey records", "Minya antiquities office"],
        "contributor": "laila",
        "addedAgo": "1 month ago",
        "saves": 198,
        "photos": 8,
        "rating": 4.6,
        "ratingCount": 25,
        "verified": False,
        "featured": True,
        "popular": False,
        "visitMinutes": 60,
        "distanceKm": 2.0,
    },
    {
        "id": "tuna-el-gebel",
        "name": "Tuna El-Gebel — Gateway of the Necropolis",
        "category": "Historical Sites",
        "governorate": "Minya",
        "region": "Northern Upper Egypt",
        "period": "Greco-Roman",
        "approxDate": "c. 300 BCE",
        "city": "Minya",
        "lat": 27.7181,
        "lng": 30.6989,
        "image": "tuna-el-gebel",
        "gallery": ["tuna-el-gebel", "beni-hasan", "place-temple"],
        "summary": "The painted chapel of Petosiris and the Bab el-Ma'abka, with its mysterious catacombs of sacred ibis mummies, sit at the edge of the desert.",
        "description": "The western cemetery of Hermopolis preserves the painted chapel of Petosiris, blending Egyptian and Greek artistic styles, and the Bab el-Ma'abka — a gate the Romans called the 'door of the catacombs', full of ibis mummies. The site includes the tomb of Isadora and a sprawling underground network. Its edge-of-desert setting makes it one of Middle Egypt's most atmospheric places.",
        "keyFacts": [
            "Painted chapel of Petosiris",
            "Catacombs of sacred ibis mummies",
            "Tomb of Isadora with glass coffin",
            "Roman-era 'door of the catacombs'",
            "Rare Egyptian-Greek mixed style",
        ],
        "timeline": [
            "c. 300 BCE — chapel of Petosiris",
            "Roman era — extended catacombs",
            "1900s — first excavations",
            "Today — open site with visitor centre",
        ],
        "architecture": [
            "Chapel with painted columns",
            "Underground galleries of niches",
            "Pyramid-topped Roman gate",
        ],
        "stories": [
            "The ibis was sacred to Thoth, and pilgrims travelled from all over Egypt to bury their birds here — the galleries once held hundreds of thousands.",
        ],
        "sources": ["Ashmolean archive", "Minya antiquities office"],
        "contributor": "dina",
        "addedAgo": "1 week ago",
        "saves": 302,
        "photos": 13,
        "rating": 4.7,
        "ratingCount": 41,
        "verified": True,
        "featured": False,
        "popular": False,
        "visitMinutes": 120,
        "distanceKm": 4.5,
    },
    {
        "id": "deir-el-medina",
        "name": "Deir El-Medina — The Village of the Artisans",
        "category": "Hidden Gems",
        "governorate": "Luxor",
        "region": "Southern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1500 BCE",
        "city": "Luxor",
        "lat": 25.7283,
        "lng": 32.6019,
        "image": "deir-el-medina",
        "gallery": ["deir-el-medina", "place-temple", "beni-hasan"],
        "summary": "The walled workers' village that built the Valley of the Kings, whose family tombs hold some of Egypt's most vivid personal paintings.",
        "description": "A walled village built for the craftsmen who carved the royal tombs across the mountain. Its streets and houses are gone, but the family tombs of its inhabitants survive with unusually personal scenes — painted gardens, cats, and dinners with friends. Legal records found here tell of strikes, love affairs, and court cases: ancient Egypt's most human archive.",
        "keyFacts": [
            "Home of the artisans who built the royal tombs",
            "Family tombs with personal scenes",
            "Huge archive of everyday legal records",
            "Includes the famous 'strike' records",
            "Well-preserved painted ceilings",
        ],
        "timeline": [
            "c. 1500 BCE — village founded",
            "c. 1200 BCE — tomb of Sennedjem built",
            "1900s — excavation of the archive",
            "Today — restored visitor site",
        ],
        "architecture": [
            "Painted family tombs with chapels",
            "Small pyramid tomb-tops",
            "Walled village plan",
        ],
        "stories": [
            "The tomb of Sennedjem shows the craftsman and his wife harvesting in paradise; his grandson left a note about the family's cat.",
        ],
        "sources": ["Luxor antiquities office", "Theban Mapping Project"],
        "contributor": "youssef",
        "addedAgo": "2 weeks ago",
        "saves": 521,
        "photos": 19,
        "rating": 4.9,
        "ratingCount": 88,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 90,
        "distanceKm": 3.0,
    },
    {
        "id": "madinet-madi",
        "name": "Madinet Madi — The Lost City of the Goddess",
        "category": "Hidden Gems",
        "governorate": "Faiyum",
        "region": "Lower Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1850 BCE",
        "city": "Faiyum",
        "lat": 29.2461,
        "lng": 30.5144,
        "image": "madinet-madi",
        "gallery": ["madinet-madi", "qasr-el-sagha", "place-temple"],
        "summary": "A well-preserved Middle Kingdom temple to Renenutet, the cobra goddess of the harvest, rising from the Faiyum fields.",
        "description": "The most complete Middle Kingdom temple in Egypt, dedicated to Renenutet, the cobra goddess of harvest and granaries, and to Sobek. Its pylon still stands with limestone columns, and its walls carry scenes of Pharaoh Amenemhat III. Located in the Faiyum, it is often almost empty of visitors.",
        "keyFacts": [
            "Most complete Middle Kingdom temple in Egypt",
            "Dedicated to Renenutet and Sobek",
            "Pylon with limestone columns",
            "Scenes of Amenemhat III",
            "Rarely crowded",
        ],
        "timeline": [
            "c. 1850 BCE — founded under Amenemhat III",
            "Greco-Roman era — expanded with processional way",
            "1900s — first excavation",
            "Today — open site, quiet",
        ],
        "architecture": [
            "Raised pylon and columned court",
            "Processional way with statues",
            "Cobra-headed columns in places",
        ],
        "stories": [
            "The site was built for a snake goddess — carved cobras still watch the processional way.",
        ],
        "sources": ["Faiyum antiquities office", "Excavation reports"],
        "contributor": "omar",
        "addedAgo": "3 weeks ago",
        "saves": 176,
        "photos": 10,
        "rating": 4.5,
        "ratingCount": 22,
        "verified": False,
        "featured": False,
        "popular": False,
        "visitMinutes": 60,
        "distanceKm": 2.5,
    },
    {
        "id": "qasr-el-sagha",
        "name": "Qasr El-Sagha — The Desert Temple of Mystery",
        "category": "Stories & Legends",
        "governorate": "Faiyum",
        "region": "Lower Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1500 BCE",
        "city": "Faiyum",
        "lat": 29.5811,
        "lng": 30.5931,
        "image": "qasr-el-sagha",
        "gallery": ["qasr-el-sagha", "madinet-madi", "place-temple"],
        "summary": "An unfinished desert temple with doors that open onto blank walls and no known dedication — its purpose still debated.",
        "description": "A mysterious unfinished temple in the desert north of the Faiyum. Its rough walls have doors that open onto blank chambers, and no inscription names its god — leading to its Arabic name, Qasr el-Sagha, the Goldsmith's Palace. Some see a solar alignment, others a workshop. It remains one of Egypt's strangest enigmas.",
        "keyFacts": [
            "Unfinished temple of unknown dedication",
            "Doors that open onto blank walls",
            "Name means 'Goldsmith's Palace'",
            "Debated astronomical alignments",
            "No cartouche or inscription found",
        ],
        "timeline": [
            "c. 1500 BCE — construction began and halted",
            "19th c. — visited and named",
            "1990s — alignment studies",
            "Today — open desert site",
        ],
        "architecture": [
            "Rough limestone walls, unadorned",
            "Seven doorways opening onto solid walls",
            "Rectangular desert plan",
        ],
        "stories": [
            "Locals say gold was hidden here by a craftsman who never returned; the name came from his trade.",
        ],
        "sources": ["Faiyum antiquities office", "Field survey notes"],
        "contributor": "karim",
        "addedAgo": "1 month ago",
        "saves": 245,
        "photos": 12,
        "rating": 4.4,
        "ratingCount": 27,
        "verified": False,
        "featured": True,
        "popular": False,
        "visitMinutes": 60,
        "distanceKm": 3.0,
    },
    {
        "id": "meidum",
        "name": "The Collapsed Pyramid of Meidum",
        "category": "Historical Sites",
        "governorate": "Beni Suef",
        "region": "Lower Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 2600 BCE",
        "city": "Meidum",
        "lat": 29.3885,
        "lng": 31.1583,
        "image": "meidum",
        "gallery": ["meidum", "qasr-el-sagha", "place-temple"],
        "summary": "A step pyramid that collapsed into its own rubble, leaving a mysterious three-tier tower of smooth casing above a field of debris.",
        "description": "A pyramid that tried to be the first true pyramid and collapsed — leaving a striking three-step tower of smooth casing floating above a sea of rubble. Its burial chamber is unique, its mastabas are superb, and its fate is a mystery. The pyramid was probably never finished; its distinctive look makes it one of the most photogenic in Egypt.",
        "keyFacts": [
            "An early step pyramid turned true pyramid",
            "Collapsed in antiquity, leaving the famous 'tower'",
            "Unique corbel-vaulted burial chamber",
            "Field of well-cut mastabas around it",
            "On the edge of the Faiyum road",
        ],
        "timeline": [
            "c. 2600 BCE — construction begins",
            "Antiquity — outer shell collapses",
            "1882 — Mastabat Fara'un explored",
            "Today — open site",
        ],
        "architecture": [
            "Smooth casing over a step core",
            "Corbelled burial chamber",
            "Surrounding mastaba field",
        ],
        "stories": [
            "It stands today the way it was left: half pyramid, half ruin, with the desert slowly burying the pieces.",
        ],
        "sources": ["Beni Suef antiquities office", "Mastaba field surveys"],
        "contributor": "youssef",
        "addedAgo": "5 days ago",
        "saves": 402,
        "photos": 18,
        "rating": 4.7,
        "ratingCount": 63,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 90,
        "distanceKm": 3.2,
    },
    {
        "id": "deir-el-muharraq",
        "name": "Deir El-Muharraq — The First Monastery",
        "category": "Religious Heritage",
        "governorate": "Asyut",
        "region": "Upper Egypt",
        "period": "Coptic",
        "approxDate": "4th century CE",
        "city": "Qusiya",
        "lat": 27.3908,
        "lng": 30.7903,
        "image": "deir-el-muharraq",
        "gallery": ["deir-el-muharraq", "place-coptic", "place-temple"],
        "summary": "A living 4th-century monastery claiming the oldest altar in Egypt, active for over 1,600 continuous years.",
        "description": "One of the oldest continuously inhabited monasteries in the world, founded in the 4th century. Its great church is held to preserve the oldest altar in Egypt, and a chapel within claims to mark where the Holy Family rested on their journey. Its domed churches and mud-brick enclosure make it a place of pilgrimage to this day.",
        "keyFacts": [
            "Founded in the 4th century CE",
            "Claims the oldest altar in Egypt",
            "Chapel marks a Holy Family resting place",
            "Continuously inhabited for 1,600+ years",
            "Enclosed by a massive mud-brick wall",
        ],
        "timeline": [
            "4th c. — founding",
            "1850s — church of the Virgin rebuilt",
            "1900s — monastery archive assembled",
            "Today — active pilgrimage site",
        ],
        "architecture": [
            "Three churches in one enclosure",
            "Massive mud-brick defensive wall",
            "Ancient palm-beam roofs",
        ],
        "stories": [
            "The Holy Family tradition: the family rested here, and the altar under the sanctuary marks the spot.",
        ],
        "sources": ["Coptic Orthodox archives", "Asyut antiquities office"],
        "contributor": "mahmoud",
        "addedAgo": "2 weeks ago",
        "saves": 267,
        "photos": 11,
        "rating": 4.8,
        "ratingCount": 35,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 2.0,
    },
    {
        "id": "wadi-natrun",
        "name": "The Desert Monasteries of Wadi El-Natrun",
        "category": "Religious Heritage",
        "governorate": "Beheira",
        "region": "Nile Delta fringe",
        "period": "Coptic",
        "approxDate": "4th century CE",
        "city": "Wadi El-Natrun",
        "lat": 30.3428,
        "lng": 30.3600,
        "image": "wadi-natrun",
        "gallery": ["wadi-natrun", "place-coptic", "fort-julien"],
        "summary": "Four working monasteries in the salt valley of the desert fathers, some with medieval towers painted with saints.",
        "description": "The salt-flat depression between Cairo and Alexandria once hosted hundreds of monastic communities; four survive, all still active. Their fort-like towers and domed churches hold medieval icons and libraries. The valley's very name comes from its natron lakes, the ancient source of Egyptian salt.",
        "keyFacts": [
            "Four surviving ancient monasteries",
            "Medieval towers painted with saints",
            "Ancient icons and library collections",
            "Natron lakes gave the valley its name",
            "Cradle of early monasticism",
        ],
        "timeline": [
            "4th c. — desert fathers settle",
            "9th c. — monastic libraries flourish",
            "19th c. — European scholars visit",
            "Today — active monasteries and tourism",
        ],
        "architecture": [
            "Fortified keep-towers",
            "Domed churches with ancient icons",
            "Mud-brick enclosure walls",
        ],
        "stories": [
            "A monk's cell wall still carries a scratch-mark calendar counting 14 centuries of fasts.",
        ],
        "sources": ["Coptic archives", "Beheira tourism office"],
        "contributor": "mahmoud",
        "addedAgo": "1 week ago",
        "saves": 338,
        "photos": 15,
        "rating": 4.8,
        "ratingCount": 47,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 150,
        "distanceKm": 3.0,
    },
    {
        "id": "al-qasr-dakhla",
        "name": "Al-Qasr — The Clay Village of Dakhla",
        "category": "Hidden Gems",
        "governorate": "New Valley",
        "region": "Western Desert",
        "period": "Ottoman",
        "approxDate": "16th century CE",
        "city": "Dakhla Oasis",
        "lat": 25.5114,
        "lng": 28.9833,
        "image": "al-qasr-dakhla",
        "gallery": ["al-qasr-dakhla", "shali-siwa", "place-nubian"],
        "summary": "A medieval clay village of arched lanes and wooden doors, still lived in after six centuries.",
        "description": "A medieval village of mud-brick towers and houses, its narrow lanes roofed in palm trunks, built in the 16th century and still partially inhabited. Its wooden doors and mashrabiya windows open onto vaulted passages that once held every workshop of a self-sufficient oasis town. Locals still live in its older rooms, sharing space with a 900-year-old minaret.",
        "keyFacts": [
            "16th-century clay village, still lived in",
            "Vaulted lanes roofed in palm trunks",
            "900-year-old minaret",
            "Original wooden doors and mashrabiya",
            "In the Western Desert oasis of Dakhla",
        ],
        "timeline": [
            "16th c. — settlement consolidates",
            "19th c. — market and workshops flourish",
            "1960s — new town built nearby",
            "Today — heritage village with guesthouses",
        ],
        "architecture": [
            "Multi-storey mud-brick houses",
            "Vaulted passageways and lanes",
            "Hanging mosque and minaret",
        ],
        "stories": [
            "The lanes were built narrow so that two men with swords could not fight side by side — and so the summer heat could not enter.",
        ],
        "sources": ["New Valley antiquities office", "Desert heritage survey"],
        "contributor": "sara",
        "addedAgo": "3 weeks ago",
        "saves": 412,
        "photos": 20,
        "rating": 4.8,
        "ratingCount": 56,
        "verified": True,
        "featured": True,
        "popular": True,
        "visitMinutes": 120,
        "distanceKm": 1.5,
    },
    {
        "id": "hibis-temple",
        "name": "The Temple of Hibis in the Great Sand Sea",
        "category": "Historical Sites",
        "governorate": "New Valley",
        "region": "Western Desert",
        "period": "Greco-Roman",
        "approxDate": "6th c. BCE – 4th c. CE",
        "city": "Kharga Oasis",
        "lat": 25.4833,
        "lng": 30.5500,
        "image": "hibis-temple",
        "gallery": ["hibis-temple", "white-desert", "place-temple"],
        "summary": "Egypt's best-preserved desert temple, built over a thousand years and recently rescued from the encroaching sand.",
        "description": "The best-preserved temple in Egypt's Western Desert, built from the Persian period through the Ptolemies — more than a thousand years of construction. Its walls carry unique religious scenes, including a ceiling carved with the sky goddess Nut. For decades the sand sea crept up its walls; a recent UNESCO-backed project pumped the sand away and restored its colours.",
        "keyFacts": [
            "Best-preserved temple in the Western Desert",
            "Built over 1,000 years of rulers",
            "Unique carved ceiling of Nut",
            "Recently rescued from the encroaching sand",
            "Persian, Ptolemaic and Roman layers",
        ],
        "timeline": [
            "6th c. BCE — founding under the Persians",
            "Ptolemaic era — major expansion",
            "1980s — sand reaches the columns",
            "2010s — UNESCO restoration removes the sand",
        ],
        "architecture": [
            "Sandstone temple with peristyle court",
            "Carved ceiling of Nut",
            "Processional sphinx avenue in part",
        ],
        "stories": [
            "For years only the top of the temple's gate showed above the dunes; boatmen of the desert called it the sail of a stone ship.",
        ],
        "sources": ["UNESCO project records", "New Valley antiquities office"],
        "contributor": "sara",
        "addedAgo": "1 week ago",
        "saves": 290,
        "photos": 14,
        "rating": 4.7,
        "ratingCount": 39,
        "verified": True,
        "featured": True,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 4.0,
    },
    {
        "id": "kom-el-shoqafa",
        "name": "The Catacombs of Kom El-Shoqafa",
        "category": "Historical Sites",
        "governorate": "Alexandria",
        "region": "Lower Egypt",
        "period": "Greco-Roman",
        "approxDate": "2nd century CE",
        "city": "Alexandria",
        "lat": 31.2044,
        "lng": 29.8969,
        "image": "kom-el-shoqafa",
        "gallery": ["kom-el-shoqafa", "pompeys-pillar", "place-temple"],
        "summary": "A multi-level Roman necropolis where Egyptian and Greek art blend in carved chambers now lit for visitors.",
        "description": "The largest Roman funerary complex in Egypt, cut into three levels of rock and blending Egyptian and Greek motifs in a unique style. A spiral staircase leads to a rotunda and a banquet hall where families once feasted with the dead. Its walls carry serpents, Medusa, and Egyptian gods side by side.",
        "keyFacts": [
            "Largest Roman necropolis in Egypt",
            "Three rock-cut levels",
            "Egyptian-Greek mixed iconography",
            "Caracalla Hall for family feasts",
            "Discovered by accident in 1900",
        ],
        "timeline": [
            "2nd c. CE — construction",
            "1900 — discovered accidentally",
            "1995 — opened as a public site",
            "Today — museum and visitor centre",
        ],
        "architecture": [
            "Spiral staircase to the burial level",
            "Rotunda and banquet hall",
            "Triclinium and niches",
        ],
        "stories": [
            "It was discovered when a donkey's legs slipped into a hole that opened onto the chambers below.",
        ],
        "sources": ["Alexandria antiquities office", "Greco-Roman Museum archive"],
        "contributor": "omar",
        "addedAgo": "4 days ago",
        "saves": 477,
        "photos": 22,
        "rating": 4.8,
        "ratingCount": 71,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 90,
        "distanceKm": 2.0,
    },
    {
        "id": "pompeys-pillar",
        "name": "Pompey's Pillar",
        "category": "Stories & Legends",
        "governorate": "Alexandria",
        "region": "Lower Egypt",
        "period": "Greco-Roman",
        "approxDate": "3rd century CE",
        "city": "Alexandria",
        "lat": 31.1841,
        "lng": 29.8964,
        "image": "pompeys-pillar",
        "gallery": ["pompeys-pillar", "kom-el-shoqafa", "place-temple"],
        "summary": "A single 20-metre column of red Aswan granite, misnamed for Pompey and standing over the buried remains of the Serapeum.",
        "description": "A 20-metre column of red Aswan granite, erected in the 3rd century and named for Pompey by crusaders who misread its inscription. It stands on the site of the Serapeum, the great temple to Serapis, whose subterranean corridors survive below. Its capital alone weighs nearly 30 tonnes, and it is the tallest ancient column in Egypt.",
        "keyFacts": [
            "Tallest ancient column in Egypt (20m)",
            "Red Aswan granite, single block",
            "Erected in the 3rd century CE",
            "Stands over the Serapeum's corridors",
            "Named for Pompey by crusaders",
        ],
        "timeline": [
            "3rd c. CE — erected under Diocletian",
            "12th–13th c. — crusaders rename it",
            "19th c. — first recorded measurements",
            "Today — open site beside the catacombs",
        ],
        "architecture": [
            "Single 20-metre granite column",
            "Carved capital and base",
            "Subterranean Serapeum chambers",
        ],
        "stories": [
            "The name is a mistake that stuck: the column never had anything to do with Pompey, who died in Egypt a century earlier.",
        ],
        "sources": ["Alexandria antiquities office", "Classical sources"],
        "contributor": "omar",
        "addedAgo": "6 days ago",
        "saves": 354,
        "photos": 16,
        "rating": 4.6,
        "ratingCount": 49,
        "verified": True,
        "featured": False,
        "popular": False,
        "visitMinutes": 45,
        "distanceKm": 1.5,
    },
    {
        "id": "gayer-anderson",
        "name": "The Gayer-Anderson House",
        "category": "Architecture",
        "governorate": "Cairo",
        "region": "Cairo",
        "period": "Ottoman",
        "approxDate": "17th century CE",
        "city": "Cairo",
        "lat": 30.0322,
        "lng": 31.2244,
        "image": "gayer-anderson",
        "gallery": ["gayer-anderson", "sultan-hassan", "place-palace"],
        "summary": "Two fused Ottoman mansions whose mashrabiya screens and painted ceilings were once home to a British major's private collection.",
        "description": "Two joined Ottoman mansions of the 17th century, opened as a house museum. Their mashrabiya screens, carved ceilings, and marble courtyards preserve the domestic architecture of old Cairo at its richest. The British Major Gayer-Anderson lived here in the 1930s and filled it with his own collection, keeping the rooms as a working home.",
        "keyFacts": [
            "Two fused 17th-century Ottoman mansions",
            "Superb mashrabiya screens and ceilings",
            "Major Gayer-Anderson lived here in the 1930s",
            "Cat statue said to bring luck",
            "Behind the Mosque of Ibn Tulun",
        ],
        "timeline": [
            "17th c. — houses built",
            "1935 — opened as a museum",
            "1940s — collection expanded",
            "Today — national museum house",
        ],
        "architecture": [
            "Mashrabiya screens and wind catches",
            "Painted and gilded ceilings",
            "Courtyards with marble floors",
        ],
        "stories": [
            "A carved cat in the courtyard is said to bring luck to anyone who touches its tail — it is worn smooth from the practice.",
        ],
        "sources": ["Cairo antiquities office", "House museum archive"],
        "contributor": "mostafa",
        "addedAgo": "2 weeks ago",
        "saves": 391,
        "photos": 24,
        "rating": 4.8,
        "ratingCount": 82,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 90,
        "distanceKm": 0.4,
    },
    {
        "id": "sultan-hassan",
        "name": "The Mosque-Madrasa of Sultan Hassan",
        "category": "Architecture",
        "governorate": "Cairo",
        "region": "Cairo",
        "period": "Mamluk",
        "approxDate": "1363 CE",
        "city": "Cairo",
        "lat": 30.0324,
        "lng": 31.2569,
        "image": "sultan-hassan",
        "gallery": ["sultan-hassan", "gayer-anderson", "place-mosque"],
        "summary": "A Mamluk colossus of stone whose monumental entrance and 34-metre dome make it a landmark of medieval Cairo's skyline.",
        "description": "One of the largest and finest Mamluk buildings in the world, with a monumental portal crowned by muqarnas and a dome 34 metres tall. Built to house four law schools around a cruciform courtyard, its walls rise sheer and severe. It is considered the most perfect example of Mamluk monumental architecture in Cairo.",
        "keyFacts": [
            "One of the largest Mamluk buildings in the world",
            "34-metre dome over the mausoleum",
            "Housed four schools of Islamic law",
            "Monumental muqarnas portal",
            "Built 1356–1363",
        ],
        "timeline": [
            "1356 — construction begins",
            "1363 — completed",
            "14th c. — Sultan Hassan disappears",
            "Today — restored and open",
        ],
        "architecture": [
            "Cruciform four-iwan plan",
            "Grand muqarnas portal",
            "Towering 34-metre dome",
        ],
        "stories": [
            "The sultan who built it vanished without trace; some say he was taken by the very eunuchs he appointed, and the dome is his empty tomb.",
        ],
        "sources": ["Cairo antiquities office", "Mamluk architecture studies"],
        "contributor": "mostafa",
        "addedAgo": "3 weeks ago",
        "saves": 466,
        "photos": 28,
        "rating": 4.9,
        "ratingCount": 95,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 90,
        "distanceKm": 1.0,
    },
    {
        "id": "shali-siwa",
        "name": "The Shali Fortress of Siwa",
        "category": "Architecture",
        "governorate": "Matrouh",
        "region": "Western Desert",
        "period": "Ottoman",
        "approxDate": "13th century CE",
        "city": "Siwa",
        "lat": 29.2031,
        "lng": 25.5195,
        "image": "shali-siwa",
        "gallery": ["shali-siwa", "al-qasr-dakhla", "place-nubian"],
        "summary": "A 13th-century fortress of kershef mud-salt bricks, eroded into a honeycomb of stone above the Siwa oasis.",
        "description": "The fortress of Shali was built in the 13th century from kershef — bricks of salt and mud — and rose several storeys above Siwa's palm groves. Heavy rains in 1926 partly dissolved the town, and it was abandoned for the lower village, leaving a ghostly honeycomb on the ridge. Its eroded towers are the symbol of Siwa today.",
        "keyFacts": [
            "13th-century desert fortress",
            "Built of kershef (salt and mud) bricks",
            "Partially dissolved by 1926 rains",
            "Honeycomb of eroded towers remains",
            "Symbol of the Siwa oasis",
        ],
        "timeline": [
            "13th c. — fortress built",
            "1926 — heavy rains partly dissolve it",
            "1960s — fully abandoned",
            "Today — open site, lit at night",
        ],
        "architecture": [
            "Multi-storey kershef houses",
            "Narrow defensive lanes",
            "Honeycombed eroded towers",
        ],
        "stories": [
            "The salt of the walls tastes of the lake below; after the great rain, villagers said the town 'melted back into the ground it came from'.",
        ],
        "sources": ["Matrouh antiquities office", "Siwa heritage archive"],
        "contributor": "sara",
        "addedAgo": "1 month ago",
        "saves": 523,
        "photos": 26,
        "rating": 4.8,
        "ratingCount": 68,
        "verified": True,
        "featured": True,
        "popular": True,
        "visitMinutes": 60,
        "distanceKm": 1.0,
    },
    {
        "id": "gebel-el-silsila",
        "name": "The Quarries of Gebel El-Silsila",
        "category": "Hidden Gems",
        "governorate": "Aswan",
        "region": "Southern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 1450 BCE",
        "city": "Aswan",
        "lat": 24.6361,
        "lng": 32.9314,
        "image": "gebel-el-silsila",
        "gallery": ["gebel-el-silsila", "el-kab", "place-temple"],
        "summary": "The vast river-side quarry that supplied Egypt's temples, with monumental stelae and a rock-cut sanctuary of Horemheb.",
        "description": "The great sandstone quarry of the Nile between Aswan and Edfu, whose rock built the temples of Upper Egypt. Its cliffs are carved with the hieroglyphs of kings who came to mark their quarries, and a rock-cut sanctuary of Horemheb lines the river. The wide, quiet channel here is also where the Nile narrows — the name means 'the chain of the mountain'.",
        "keyFacts": [
            "Egypt's main sandstone quarry",
            "Rock-cut sanctuary of Horemheb",
            "Carved quarry stelae of many kings",
            "Nile narrows dramatically here",
            "Working quarry until Roman times",
        ],
        "timeline": [
            "c. 1450 BCE — quarrying in earnest",
            "14th c. BCE — Horemheb's sanctuary",
            "Roman era — stone still cut",
            "Today — open site and river cruise stop",
        ],
        "architecture": [
            "Rock-cut sanctuary chambers",
            "Colossal quarry stelae",
            "Ancient tool marks preserved",
        ],
        "stories": [
            "The site's name comes from the ancient belief that a chain across the river here held back the floodwaters.",
        ],
        "sources": ["Aswan antiquities office", "Quarry survey project"],
        "contributor": "youssef",
        "addedAgo": "2 weeks ago",
        "saves": 218,
        "photos": 13,
        "rating": 4.6,
        "ratingCount": 30,
        "verified": True,
        "featured": False,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 3.0,
    },
    {
        "id": "el-kab",
        "name": "El-Kab — The Forgotten City of the South",
        "category": "Hidden Gems",
        "governorate": "Aswan",
        "region": "Southern Upper Egypt",
        "period": "Pharaonic",
        "approxDate": "c. 3000 BCE",
        "city": "Aswan",
        "lat": 25.1167,
        "lng": 32.8000,
        "image": "el-kab",
        "gallery": ["el-kab", "gebel-el-silsila", "place-temple"],
        "summary": "A walled ancient city with tombs and a rare temple of Nekhbet, the vulture goddess, largely empty of visitors.",
        "description": "The ancient city of Nekheb, one of Egypt's most important and least-visited sites. Enclosed by enormous mud-brick walls, it preserves the temple of Nekhbet, the vulture goddess of Upper Egypt, and rock-cut tombs with rich painted scenes. The site is so quiet that shepherds graze sheep among the ruins.",
        "keyFacts": [
            "Ancient city of Nekheb",
            "Temple of the vulture goddess Nekhbet",
            "Enormous mud-brick enclosure walls",
            "Painted rock-cut tombs",
            "Almost empty of visitors",
        ],
        "timeline": [
            "c. 3000 BCE — early settlement",
            "Predynastic — one of Egypt's oldest towns",
            "18th Dynasty — temple of Nekhbet rebuilt",
            "Today — open, quiet site",
        ],
        "architecture": [
            "Massive mud-brick walls",
            "Temple of Nekhbet",
            "Rock-cut tomb chapels",
        ],
        "stories": [
            "The walls of the ancient city still stand in places as high as a house — and no one is quite sure when they were last repaired.",
        ],
        "sources": ["Aswan antiquities office", "Nekheb survey"],
        "contributor": "youssef",
        "addedAgo": "3 weeks ago",
        "saves": 161,
        "photos": 9,
        "rating": 4.5,
        "ratingCount": 19,
        "verified": False,
        "featured": False,
        "popular": False,
        "visitMinutes": 90,
        "distanceKm": 2.5,
    },
    {
        "id": "bab-zuweila",
        "name": "Bab Zuweila — The Gate of the Hanged",
        "category": "Historical Sites",
        "governorate": "Cairo",
        "region": "Cairo",
        "period": "Mamluk",
        "approxDate": "1092 CE",
        "city": "Cairo",
        "lat": 30.0427,
        "lng": 31.2572,
        "image": "bab-zuweila",
        "gallery": ["bab-zuweila", "sultan-hassan", "gayer-anderson"],
        "summary": "The last surviving gate of medieval Cairo, climbable for sunset views over the old city, and scene of executions and victory processions.",
        "description": "The only surviving gate of the southern wall of medieval Cairo, built in 1092 and crowned by two minarets that can be climbed for the city's best sunset view. For centuries it was the ceremonial entrance for returning armies — and the site of public executions, giving it the nickname 'the gate of the hanged'.",
        "keyFacts": [
            "Only surviving gate of old Cairo's walls",
            "Built 1092 CE",
            "Climbable minarets with sunset views",
            "Scene of victory processions and executions",
            "Standing between Darb al-Ahmar districts",
        ],
        "timeline": [
            "1092 — built under the Fatimids",
            "15th c. — executions at the gate",
            "1930s — monument restored",
            "Today — open to climbers",
        ],
        "architecture": [
            "Twin minarets added in 1415",
            "Massive stone gate with arches",
            "Climbing stair to the rooftop",
        ],
        "stories": [
            "Heads of executed officials were displayed here; the folk nickname of the gate never faded.",
        ],
        "sources": ["Cairo antiquities office", "Medieval Cairo studies"],
        "contributor": "mostafa",
        "addedAgo": "1 week ago",
        "saves": 389,
        "photos": 21,
        "rating": 4.7,
        "ratingCount": 58,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 60,
        "distanceKm": 0.6,
    },
    {
        "id": "khayamiya-street",
        "name": "Street of the Tentmakers",
        "category": "Traditional Crafts",
        "governorate": "Cairo",
        "region": "Cairo",
        "period": "Mamluk",
        "approxDate": "17th century CE",
        "city": "Cairo",
        "lat": 30.0392,
        "lng": 31.2589,
        "image": "khayamiya",
        "gallery": ["khayamiya", "bab-zuweila", "fishawy"],
        "summary": "A covered 17th-century lane where appliqué panels are still hand-stitched by artisans, as they have been for centuries.",
        "description": "A single covered street in old Cairo where the khayyamiya, the tentmakers, still sew the traditional appliqué panels by hand. Each panel — bold flowers, Islamic patterns, or Arabic calligraphy — takes days of stitching. The street has been the guild's home since the 17th century, and the craft is now UNESCO-listed.",
        "keyFacts": [
            "Covered 17th-century craft street",
            "Hand-stitched appliqué panels",
            "UNESCO-recognised living craft",
            "Some workshops centuries old",
            "Panels made in tiny patchwork squares",
        ],
        "timeline": [
            "17th c. — tentmakers' guild established",
            "19th c. — street covered against sun",
            "2000s — craft listed by UNESCO",
            "Today — working workshops open to visitors",
        ],
        "architecture": [
            "Covered street of workshops",
            "Facades hung with panels",
            "Centuries-old wooden shopfronts",
        ],
        "stories": [
            "Some panels are stitched in secret to the customer's family name — the pattern hides a signature visible only to those who know to look.",
        ],
        "sources": ["UNESCO listing", "Cairo craft guild archive"],
        "contributor": "mostafa",
        "addedAgo": "5 days ago",
        "saves": 476,
        "photos": 30,
        "rating": 4.8,
        "ratingCount": 64,
        "verified": True,
        "featured": True,
        "popular": True,
        "visitMinutes": 60,
        "distanceKm": 0.4,
    },
    {
        "id": "fishawy-cafe",
        "name": "El Fishawy — The Mirror of Old Cairo",
        "category": "Food & Culture",
        "governorate": "Cairo",
        "region": "Cairo",
        "period": "Modern",
        "approxDate": "1797 CE",
        "city": "Cairo",
        "lat": 30.0458,
        "lng": 31.2600,
        "image": "fishawy",
        "gallery": ["fishawy", "khayamiya", "place-palace"],
        "summary": "Cairo's most famous coffeehouse, open for over two centuries beside the El-Hussein Mosque in the heart of the old city.",
        "description": "Founded in 1797 in the alley beside the El-Hussein Mosque, El Fishawy has served coffee, tea and shisha to two centuries of Cairenes and travellers. Its mirrored walls and hanging brass lamps make the small rooms glow at any hour. The cafe never closes its doors — someone is always drinking tea there, day or night.",
        "keyFacts": [
            "Founded 1797, over 220 years of service",
            "Famous mirrored walls and brass lamps",
            "Open around the clock",
            "Beside the El-Hussein Mosque",
            "Serves traditional coffees and teas",
        ],
        "timeline": [
            "1797 — founded",
            "20th c. — poets and writers make it famous",
            "1992 — restored after earthquake",
            "Today — landmark of Old Cairo",
        ],
        "architecture": [
            "Mirrored walls and hanging brass lamps",
            "Cramped, glowing rooms",
            "Open wooden benches",
        ],
        "stories": [
            "Nobel laureate Naguib Mahfouz wrote scenes of Cairo in these booths — the cafe still sets his favourite table aside in some accounts.",
        ],
        "sources": ["Cairo heritage lists", "Cafe's own history"],
        "contributor": "mostafa",
        "addedAgo": "4 days ago",
        "saves": 642,
        "photos": 34,
        "rating": 4.8,
        "ratingCount": 104,
        "verified": True,
        "featured": False,
        "popular": True,
        "visitMinutes": 60,
        "distanceKm": 0.2,
    },
    {
        "id": "white-desert",
        "name": "The White Desert of Farafra",
        "category": "Natural Heritage",
        "governorate": "New Valley",
        "region": "Western Desert",
        "period": "Prehistoric",
        "approxDate": "Formed in chalk seas",
        "city": "Farafra",
        "lat": 27.0833,
        "lng": 28.4167,
        "image": "white-desert",
        "gallery": ["white-desert", "hibis-temple", "place-temple"],
        "summary": "Wind-sculpted chalk formations shaped into mushrooms and towers over 30 million years, glowing white under the desert sun.",
        "description": "The White Desert's chalk rocks were once the floor of a great sea; 30 million years of wind have carved them into mushroom-like shapes and towers. At sunset they turn rose and gold, and at night the campfires and stars make the landscape feel lunar. It is a protected national park and one of Egypt's most photographed natural wonders.",
        "keyFacts": [
            "Chalk formations carved by wind over 30 million years",
            "Part of the White Desert National Park",
            "Famous 'mushroom' rock shapes",
            "Once the floor of an ancient sea",
            "Camping under desert stars",
        ],
        "timeline": [
            "30 million years ago — sea floor",
            "Millions of years — wind carving",
            "2002 — national park declared",
            "Today — protected camping area",
        ],
        "architecture": [
            "Wind-carved chalk towers and mushrooms",
            "Crystal fields",
            "Camp-sites among the rocks",
        ],
        "stories": [
            "Campers name the largest rocks; guides recount 'the mushroom family' and the 'chicken and its chick'.",
        ],
        "sources": ["New Valley nature reserves office", "Park regulations"],
        "contributor": "sara",
        "addedAgo": "1 week ago",
        "saves": 589,
        "photos": 40,
        "rating": 4.9,
        "ratingCount": 116,
        "verified": True,
        "featured": True,
        "popular": True,
        "visitMinutes": 180,
        "distanceKm": 5.0,
    },
]

# ---------------------------------------------------------------------------
# Stories
# ---------------------------------------------------------------------------

STORIES = [
    {
        "id": "mosque-village-forgot",
        "title": "The Mosque That a Village Forgot — and Remembered",
        "excerpt": "A 16th-century minaret hidden in a courtyard wall, a family who kept the key for a century, and the spring clean that brought a whole street back to prayer.",
        "author": "Dina El-Sayed",
        "role": "Contributor",
        "readMinutes": 6,
        "date": "August 2026",
        "image": "place-mosque",
        "place": "The 'Hidden' Mosque of Al-Hamawi",
        "governorate": "Alexandria",
        "category": "Stories & Legends",
        "content": [
            {"type": "p", "text": "On a street corner in old Alexandria there is a courtyard wall that looks like every other courtyard wall in the city — pale stone, a wooden door, a pipe dripping into a drain. Behind it is a minaret that has been standing since the 16th century, and for most of the last hundred years, the people who prayed inside it were counted in single figures."},
            {"type": "p", "text": "The mosque of Al-Hamawi sits in a bend of a pedestrian lane, tucked so far off the main street that even the imams of the neighbouring mosque forgot, for a while, that it was there. Its ochre dome was painted to be visible from the sea — sailors used it as a marker — but when the sea trade moved away, so did the congregation."},
            {"type": "h2", "text": "The key in the family"},
            {"type": "p", "text": "For nearly a century the key to the mosque was kept by a single family, the Hamawi family after whom the building is named. They cleaned it, aired it, and paid for its repairs out of their own pockets. When the last of the old generation died in 2018, the family decided it was time to hand the key back — not to an institution, but to the street."},
            {"type": "p", "text": "They organized what they called 'the spring clean'. Neighbours came with buckets and brooms. The ochre dome was repainted by a house-painter who volunteered his weekend. Schoolchildren drew the mosque for a local exhibition. And on the Friday after the clean, the small prayer hall was full — standing-room only — for the first time in living memory."},
            {"type": "quote", "text": "Heritage is not what survives. It is what someone decides to keep."},
            {"type": "p", "text": "The mosque is now listed in the Alexandria heritage trail, and the minaret that could not be seen from any street until you were almost at the door has started appearing in photographs. The family still has a spare key. 'We keep it,' the youngest member told us, 'in case the door ever sticks.'"},
        ],
    },
    {
        "id": "tentmakers-needle",
        "title": "The Needle That Refuses to Retire",
        "excerpt": "Inside the Street of the Tentmakers, where panels take days to stitch and no pattern is ever quite the same, an old craft is finding a new audience.",
        "author": "Mostafa Gamal",
        "role": "Contributor",
        "readMinutes": 7,
        "date": "July 2026",
        "image": "khayamiya",
        "place": "Street of the Tentmakers",
        "governorate": "Cairo",
        "category": "Traditional Crafts",
        "content": [
            {"type": "p", "text": "The Street of the Tentmakers is a single covered lane in Cairo, and from its ceiling hang what look like hundreds of embroidered carpets. They are not carpets. They are panels of khayamiya — appliqué work in which shapes are cut from coloured cloth and stitched in layers, and every one is made by hand."},
            {"type": "p", "text": "The oldest workshops on the street trace their benches back through the generations to the 17th century, when the tentmakers' guild supplied the great tents of the Ottoman court. A royal tent could take months and dozens of hands. Today the panels are smaller, but the stitching is the same: small, dense, and unbelievably patient."},
            {"type": "h2", "text": "Days for a single panel"},
            {"type": "p", "text": "A panel with a central flower and a border of calligraphy can take a single artisan four or five full days. There is no template and no machine. The artisan draws the design in chalk directly on the cloth, cuts the pieces freehand, and builds the layers up — flower over leaf, leaf over stem."},
            {"type": "p", "text": "'My grandfather taught me that the last stitch should look like the first,' one master told us, holding up a half-finished panel. 'If anyone can tell where you started, you started wrong.'"},
            {"type": "quote", "text": "The last stitch should look like the first."},
            {"type": "p", "text": "The street now sells to tourists and collectors, and the craft is listed by UNESCO as an element of Egypt's living heritage. But the masters insist the panels are not souvenirs. 'They are records,' one said. 'Every one records a day of sitting in this light, a week of somebody's life.'"},
        ],
    },
    {
        "id": "salt-city",
        "title": "The City That Melted Back Into the Ground",
        "excerpt": "Shali was built from salt and mud, dissolved in a single great rain, and abandoned. But the fortress of Siwa was never really lost.",
        "author": "Sara Ibrahim",
        "role": "Contributor",
        "readMinutes": 5,
        "date": "June 2026",
        "image": "shali-siwa",
        "place": "The Shali Fortress of Siwa",
        "governorate": "Matrouh",
        "category": "Stories & Legends",
        "content": [
            {"type": "p", "text": "The fortress of Shali rises above the palm groves of Siwa like a cliff that grew a town on top of itself. It is built from kershef — blocks of salt and mud pressed together — and for six hundred years it was the whole of Siwa, a multi-storey city of lanes, granaries, and towers where every family lived above their own storerooms."},
            {"type": "p", "text": "The design was simple and brilliant: salt is strong as stone in the desert, where rain is a rumour. The town was built thick, against the heat of the day and the cold of the night, and its streets were narrow so the sun could not reach the bottom. Nothing was wasted — even the salt of the walls was said to taste of the lake below."},
            {"type": "h2", "text": "The rain of 1926"},
            {"type": "p", "text": "Then, in 1926, it rained. Not the usual desert sprinkle, but a proper rain that fell for days. The salt of the walls began to dissolve. People watched their houses melt — literally melt — back into the ground they had been built from. By the time the rain stopped, the town was uninhabitable, and Siwa moved down into the groves."},
            {"type": "p", "text": "The people who left did not demolish their homes. They left the honeycomb standing, and over the decades the wind finished what the rain began, carving the soft walls into the strange, beautiful ruin that stands today."},
            {"type": "quote", "text": "They left the honeycomb standing, and the wind finished what the rain began."},
            {"type": "p", "text": "Now Shali is the symbol of Siwa — lit at night, climbed by visitors, and kept by a trust of Siwi families who refuse to let it dissolve completely. The town melts, the town is repaired, and the story goes on. Salt, after all, never really disappears."},
        ],
    },
    {
        "id": "door-without-a-room",
        "title": "The Door That Opens Onto Nothing",
        "excerpt": "Somewhere in the desert north of the Faiyum stands a temple whose doors open onto blank walls. Nobody knows who built it, or why it was never finished.",
        "author": "Karim Aziz",
        "role": "Contributor",
        "readMinutes": 4,
        "date": "May 2026",
        "image": "qasr-el-sagha",
        "place": "Qasr El-Sagha — The Desert Temple of Mystery",
        "governorate": "Faiyum",
        "category": "Stories & Legends",
        "content": [
            {"type": "p", "text": "In the desert north of the Faiyum there is a building that has refused to explain itself for over three thousand years. It has doors — seven of them, tall and carefully cut — and behind almost every door there is nothing. A wall. A blank chamber. A purpose that was never finished."},
            {"type": "p", "text": "Qasr el-Sagha means 'the Goldsmith's Palace', a name given by local people who believed treasure was hidden there. No inscription, no cartouche, no statue has ever been found inside it. It is one of the only temples in Egypt with no known god."},
            {"type": "h2", "text": "Theories"},
            {"type": "p", "text": "Archaeologists have proposed a solar temple, aligned to the equinoxes. Others have suggested a fortress, or a workshop, or an observatory for a city that disappeared. The most careful studies found that the stone is unfinished — the walls were dressed once, then abandoned mid-work, as if the builders simply walked away."},
            {"type": "p", "text": "Whatever it was, it was never finished, and no one ever came back to finish it. The desert, which preserves everything, preserved instead a question."},
            {"type": "quote", "text": "The desert preserves everything — it preserved a question."},
            {"type": "p", "text": "Visitors who walk its empty rooms today describe the same feeling: that the building is waiting for something that was expected thousands of years ago. The doors open onto blank walls. The blank walls open onto the desert. And the desert, as always, keeps the secret."},
        ],
    },
    {
        "id": "saving-the-sand-ship",
        "title": "Saving the Sand-Ship of Kharga",
        "excerpt": "For decades the desert buried the Temple of Hibis one dune at a time. Then an unlikely project pumped the sand away and found colours a thousand years old.",
        "author": "Sara Ibrahim",
        "role": "Contributor",
        "readMinutes": 6,
        "date": "April 2026",
        "image": "hibis-temple",
        "place": "The Temple of Hibis in the Great Sand Sea",
        "governorate": "New Valley",
        "category": "Historical Sites",
        "content": [
            {"type": "p", "text": "The people of Kharga Oasis have a story about the great temple in the sand. When the dunes crept up around it, they said, the building became a ship sailing through a sea of sand — and for a while, only its gate showed above the waves."},
            {"type": "p", "text": "The temple of Hibis was built slowly, by many rulers over more than a thousand years, and it was the finest thing in the whole Western Desert. But the desert moves. The dunes climbed the walls, filled the rooms, and pressed on the stone with the weight of the sea."},
            {"type": "h2", "text": "The stone ship was sinking"},
            {"type": "p", "text": "By the 1980s the sand had reached the tops of the columns, and engineers warned that the weight would crush the temple's foundations. The building was collapsing under the pressure of the very element that had once preserved it. The ship was sinking."},
            {"type": "p", "text": "The rescue came from an unexpected direction: a project to pump the sand out, block by block, and to rebuild the damaged stone as it was uncovered. Teams of conservators worked where the dune had been, and under the sand they found what the desert had kept: carved ceilings, painted scenes, and colours that looked as fresh as the day they were laid."},
            {"type": "quote", "text": "The ship is no longer sinking. It sails in open air."},
            {"type": "p", "text": "Today the temple of Hibis stands clear of the sand for the first time in centuries. The people of the oasis like to say the ship has been launched — and that the desert, which so nearly took it, is the first to applaud."},
        ],
    },
    {
        "id": "second-life-village",
        "title": "The Second Life of the Painted Village",
        "excerpt": "When their island home was taken by the dam, the Nubian community rebuilt an entire village as an act of memory — and made it more colourful than the first.",
        "author": "Dina El-Sayed",
        "role": "Contributor",
        "readMinutes": 6,
        "date": "March 2026",
        "image": "place-nubian",
        "place": "The Living Nubian Village",
        "governorate": "Aswan",
        "category": "Food & Culture",
        "content": [
            {"type": "p", "text": "In the 1960s, the water of the High Dam took a thousand villages beneath it. The Nubian villages south of Aswan went first — whole towns, their palm groves, their cemeteries, their painted house-fronts, all under the lake. For the people who lost them, the memory of home became the most valuable thing they owned."},
            {"type": "p", "text": "On the West Bank of the Nile, across from Aswan, the displaced families rebuilt. And here is the strange, wonderful part: they rebuilt with more colour than before. The new villages of Gharb Aswan are painted in patterns and symbols that map the old homes — each family painted the door of their old house's colours, so the new village is also a map of the one that drowned."},
            {"type": "h2", "text": "A village that documents itself"},
            {"type": "p", "text": "The painting is not decoration. In Nubian house art, the patterns carry meaning: the palm for the date harvest, the waterbird for the river, the boat for travel, and the protective motifs that used to guard the doorway of a house that now stands at the bottom of the lake."},
            {"type": "p", "text": "The women who keep these patterns hold a library of symbols in their hands. Grandmothers teach daughters, daughters teach granddaughters, and the village walls are the pages of the book."},
            {"type": "quote", "text": "The new village is also a map of the one that drowned."},
            {"type": "p", "text": "Today the villages are known as 'the painted village', and visitors come to see them. The community welcomes them, but the painting was never for visitors. It was for the memory of a place — and it is the reason a lost world still exists, in full colour, on the walls of a new one."},
        ],
    },
    {
        "id": "incorrupt-bishop",
        "title": "The Bishop Who Would Not Decay",
        "excerpt": "In a desert monastery, under a simple stone arch, the body of a bishop lay for two centuries without decomposing. The monastery kept the arch — and the mystery.",
        "author": "Mahmoud Nasser",
        "role": "Editor",
        "readMinutes": 5,
        "date": "February 2026",
        "image": "place-coptic",
        "place": "Deir Al-Qusayr — The Last Desert Monastery",
        "governorate": "Minya",
        "category": "Stories & Legends",
        "content": [
            {"type": "p", "text": "There is a monastery in the desert east of the Nile that almost no one visits, and inside it, under a plain stone arch, there is a glass box holding the body of a bishop who died in the 1800s. The local name for the building is Deir Al-Qusayr — the Little Monastery — and it has been quiet for so long that its own fame is a rumour."},
            {"type": "p", "text": "The bishop was Sarapamon, a desert ascetic of the Coptic church. When his tomb was opened, decades after his death, his body was found intact — 'incorrupt', in the church's term. For the monks and the local people, the sign was clear, and the arch under which he lay was kept exactly where it had always been, sheltering the reliquary."},
            {"type": "h2", "text": "The arch and the earthquake"},
            {"type": "p", "text": "The monastery is also known for surviving an earthquake in the 1850s that cracked its main church. The monks rebuilt around the damage rather than demolishing it — the crack is still visible, and the arch of Sarapamon still stands. Restoration teams in the 2010s were careful to keep the arch, the reliquary, and even the crack, intact."},
            {"type": "quote", "text": "Some buildings are kept as records of what happened to them."},
            {"type": "p", "text": "Science offers explanations for incorrupt bodies — dryness, the desert's natural mummification. The faithful accept the explanations and are unmoved by them. Either way, the monastery keeps its quiet miracle in the same way it keeps its earthquake crack: unrenovated, unpolished, and exactly as it was found."},
        ],
    },
    {
        "id": "ghost-station-clock",
        "title": "The Clock That Still Ticks for a Departure",
        "excerpt": "The platform clock at Deir Sharaf station was set to the last departure when passenger service ended. A retired stationmaster still visits to make sure it runs.",
        "author": "Karim Aziz",
        "role": "Contributor",
        "readMinutes": 4,
        "date": "January 2026",
        "image": "place-railway",
        "place": "The Abandoned Station of Deir Sharaf",
        "governorate": "Minufiya",
        "category": "Hidden Gems",
        "content": [
            {"type": "p", "text": "The station clock at Deir Sharaf shows a time that no longer appears in any timetable. When the last passenger train pulled out in the 1980s, the stationmaster set the clock to the moment of departure — a small, unrepeatable act of protest — and no one has ever changed it."},
            {"type": "p", "text": "The station itself is a Victorian building of the 1890s, with arched brick doorways and a wooden ticket booth that has not sold a ticket in forty years. Freight trains still rumble through on the line; they never stop. The platform benches are original. The cast-iron columns still hold up the roof."},
            {"type": "h2", "text": "A caretaker who never retired"},
            {"type": "p", "text": "The man who set the clock, retired now, still comes to the station every week. He winds the clock. He sweeps the platform. He talks to the building the way people talk to old horses. When rail historians found him there one morning, he asked them the only question that mattered: 'Did you come to bring back the trains?'"},
            {"type": "p", "text": "The station is now a candidate in a proposed heritage railway loop that would bring tourist trains back to the Delta. If it happens, the clock will finally be allowed to move again. The retired stationmaster has already volunteered to be the first conductor."},
            {"type": "quote", "text": "Did you come to bring back the trains?"},
            {"type": "p", "text": "He keeps the platform clock set to the last departure, he says, so that whenever the first train returns, it will have something to arrive into."},
        ],
    },
    {
        "id": "needle-mirrors-fishawy",
        "title": "Tea, Mirrors, and Two Hundred Years of Conversation",
        "excerpt": "El Fishawy has been open since 1797 and never closes its doors. In its mirrored booths, Cairo has talked to itself for two centuries.",
        "author": "Mostafa Gamal",
        "role": "Contributor",
        "readMinutes": 4,
        "date": "December 2025",
        "image": "fishawy",
        "place": "El Fishawy — The Mirror of Old Cairo",
        "governorate": "Cairo",
        "category": "Food & Culture",
        "content": [
            {"type": "p", "text": "The alley beside the El-Hussein Mosque in Cairo is busy at every hour, and at its heart is a cafe that has not closed its doors since 1797. El Fishawy is not a restaurant and not a tourist stop; it is a room full of mirrors and brass lamps where, for two hundred years, the city has come to think out loud."},
            {"type": "p", "text": "The mirrors on the walls are the cafe's signature. They multiply the lamplight and the faces, so the small room seems to contain the whole history of its customers. Writers drafted novels here, singers rehearsed songs here, and travellers who sat down for ten minutes sometimes stayed for the rest of their lives."},
            {"type": "h2", "text": "The table that keeps its place"},
            {"type": "p", "text": "Ask any waiter and you will be told the cafe's most famous regular was the novelist Naguib Mahfouz, who wrote much of his portrait of Cairo in these booths. His preferred table is still pointed out with pride. Whether or not he sat there every time, the cafe has absorbed the story — which is, in its own way, as real as the mirrors."},
            {"type": "quote", "text": "The room seems to contain the whole history of its customers."},
            {"type": "p", "text": "El Fishawy's customers order the same things their great-grandparents ordered: mint tea, cardamom coffee, a shisha if the mood takes them. The ritual is the point. A city that keeps this appointment every day, in a room that never sleeps, is a city that knows itself a little better for it."},
        ],
    },
]

# ---------------------------------------------------------------------------
# Profile & community
# ---------------------------------------------------------------------------

PROFILE = {
    "name": "Mahmoud Nasser",
    "handle": "@mahmoud",
    "level": "Heritage Guide",
    "bio": "Cairo-based editor and contributor. I document the places the guidebooks skip — monasteries, workshops, and railway stations that still have stories to tell.",
    "initials": "MN",
    "memberSince": "2024",
    "discoveries": 7,
    "verified": 6,
    "photos": 48,
    "saved": 12,
    "reputation": 1240,
    "reputationParts": [{"label": "Verified records", "value": 320}, {"label": "Photos", "value": 480}, {"label": "Field visits", "value": 260}, {"label": "Story contributions", "value": 180}],
}

BADGES = [
    {"id": "first", "name": "First Discovery", "description": "Documented your first place", "icon": "map-pin", "earned": True},
    {"id": "heritage", "name": "Heritage Explorer", "description": "Visited 10 documented sites", "icon": "landmark", "earned": True},
    {"id": "storyteller", "name": "Storyteller", "description": "Published an original story", "icon": "book-open", "earned": True},
    {"id": "guide", "name": "Local Guide", "description": "Reached 50 verified contributions", "icon": "compass", "earned": True},
    {"id": "contributor", "name": "Kenzory Contributor", "description": "Reached 100 contributions", "icon": "award", "earned": False},
]

TOP_CONTRIBUTORS = [
    {"name": "Laila Hassan", "initials": "LH", "level": "Photographer", "discoveries": 24, "verified": True},
    {"name": "Mostafa Gamal", "initials": "MG", "level": "Contributor", "discoveries": 19, "verified": True},
    {"name": "Sara Ibrahim", "initials": "SI", "level": "Contributor", "discoveries": 16, "verified": True},
    {"name": "Youssef Tarek", "initials": "YT", "level": "Photographer", "discoveries": 13, "verified": True},
    {"name": "Dina El-Sayed", "initials": "DE", "level": "Contributor", "discoveries": 11, "verified": True},
]

FEED = [
    {"kind": "place", "title": "Kom El-Shoqafa reopened after restoration", "body": "The rotunda and banquet hall are lit for visitors again. Details on the new hours are in the record.", "author": "Omar Fathy", "initials": "OF", "ago": "2 hours ago", "image": "kom-el-shoqafa", "verified": True, "likes": 84, "comments": 12},
    {"kind": "story", "title": "New story: 'The Needle That Refuses to Retire'", "body": "Inside the Street of the Tentmakers, where a single panel takes days to stitch. ", "author": "Mostafa Gamal", "initials": "MG", "ago": "6 hours ago", "image": "khayamiya", "verified": True, "likes": 121, "comments": 18},
    {"kind": "place", "title": "El Fishawy documented", "body": "Two centuries of mirrors, brass lamps, and mint tea — added to Food & Culture.", "author": "Mostafa Gamal", "initials": "MG", "ago": "1 day ago", "image": "fishawy", "verified": True, "likes": 203, "comments": 31},
    {"kind": "photo", "title": "New photo set: White Desert at dusk", "body": "Forty frames from a camping trip among the chalk mushrooms.", "author": "Sara Ibrahim", "initials": "SI", "ago": "1 day ago", "image": "white-desert", "verified": True, "likes": 312, "comments": 24},
    {"kind": "place", "title": "Meidum Pyramid field notes updated", "body": "Added the mastaba field survey and corrected the burial chamber notes.", "author": "Youssef Tarek", "initials": "YT", "ago": "2 days ago", "image": "meidum", "verified": True, "likes": 97, "comments": 9},
]

SUGGESTED_SEARCHES = [
    "Hidden mosques of Cairo",
    "Monasteries of the Western Desert",
    "Nubian villages",
    "Abandoned railway stations",
    "Middle Kingdom tombs",
    "Coptic heritage",
    "Desert oases",
    "Traditional crafts streets",
]

# Place ids ordered by how recently they were added/documented (newest first).
RECENT_ORDER = [
    "kom-el-shoqafa",
    "fishawy-cafe",
    "khayamiya-street",
    "nubian-village",
    "meidum",
    "temple-of-nefertari",
    "pompeys-pillar",
    "tuna-el-gebel",
    "wadi-natrun",
    "hibis-temple",
    "white-desert",
    "bab-zuweila",
    "deir-al-qusayr",
    "deir-el-medina",
    "beni-hasan",
    "gebel-el-silsila",
    "gayer-anderson",
    "sultan-hassan",
    "deir-el-muharraq",
    "mosque-al-hamawi",
    "al-qasr-dakhla",
    "station-deir-sharaf",
    "el-kab",
    "satis-palace",
    "speos-artemidos",
    "madinet-madi",
    "qasr-el-sagha",
    "shali-siwa",
]

# ---------------------------------------------------------------------------
# Note: this module is the DEVELOPMENT SEED CONTENT source for the database.
# It is NOT used at runtime to serve pages — the application reads from the
# database. Run `flask seed` to load this content into your local database.
# ---------------------------------------------------------------------------
